heat/core/tensor.py

So far ht.randn leaves the input checking mostly to pytorch.
This patch modifies ht.randn to at least check some of the
argument properties itself.
Fixes #58

Issue #58: Make ht.randn check for sane input

---

heat/core/operations.py
heat/core/stride_tricks.py
heat/core/tensor.py
heat/core/tests/test_operations.py

Resolves issue #28 
As of now the tensor is correctly transposed, respectively its axes are permuted, and the split axes of the tensor shifts along with the permutation.
A subsequent resplit of the tensor has NOT been implemented for two reasons:
1. It might not be what the programmer wants and what would be efficient for subsequent operations
2. Resplitting the tensor is a separate operation that is part of issue #9 
It might be desirable to introduce an additional parameter called e.g. resplit to the transpose signature as soon as #9 has been implemented.

Implementation of transpose

---

heat/core/stride_tricks.py
heat/core/tests/test_stride_tricks.py

Unit tests and examples for functions broadcast_shape and sanitize_axis in stride_tricks.py
- Closes #92 and #93

Issues 92 and 93

---

heat/core/operations.py
heat/core/tensor.py
heat/core/tests/test_exponential.py
heat/core/tests/test_operations.py

Concerns #150 
Tunnels torch.allclose after check if input type is heat tensor, thus working in analogy to the numpy.allclose() (https://pytorch.org/docs/stable/torch.html#torch.allclose)
I already changed the syntax now for the sqrt tests to work on ht.allclose instead of torch.allclose

150 Implement allclose()

---

heat/core/tests/test_arithmetics.py

Fixes #164 
- Error was result of uncomplete cleanup after restructuring of binary operator generic function
- removal of faulty tensor
- tests on NotImplementedError raise are performed with T_s

Fix for test_add

---

heat/core/io.py
heat/core/operations.py
heat/core/relations.py
heat/core/tests/test_arithmetics.py
heat/core/tests/test_operations.py

This pull request will solve several issues in situations where there are more MPI ranks than the range of the spit dimension.
In particular:
Commit will fix the case tensor.comm.size>shape[tensor.split]  in function  __binary_op
in file operations.py
The original   __binary_op  will fail in case of broadcasing 
when there are ranks with empty tensors. In this case tensors are 
fetched from the the rank 0 process if needed. In case a rank contains an empty
tensor the operation will be skipped.
Commit will fix load_hdf5 for  tensor.comm.size>shape[tensor.split] in io.py

Bug/73 broadcast of   binop

---

.travis.yml

This pull request targets issue #200.
With these changes, pytest is run with mpi on 1 to 4 different processes. Each process in each run creates a unique coverage report. This in to total 10 coverage reports are bundled after finishing all test.
To achieve this behaviour I had to switch from pytest-cov to coverage.py to create the reports. 
pytest-cov was performing inconsistently and dindn't create the unique named reports for each process.
I don't see and pitfalls in changing to coverage.py.

Bundled coverage report for multiple mpi runs

---

heat/core/operations.py

Currently, there are two different interpretations, on how a float can be translated into a boolean.
The first one was by calling `byte()` but this resulted in e.g. 0.999 being translated into false which is very bad on normalized tensors where all values are between zero and one.
The other approach was to call `ceil()` on the values. The problem there is, that ceiling is very slow.
Both approaches got now exchanged by just calling `!= 0`. This results in all values equal zero to stay this way and all others to be 1.

using (t != 0) instead of t.byte()

---

heat/core/tests/test_exponential.py
heat/core/tests/test_operations.py
heat/core/tests/test_reductions.py
heat/core/tests/test_relations.py

- Addresses Issue #161 
- remove use of FLOAT_EPSILON
- compare equality using ht.allclose with intrinsic value tolerance of 1E-8

Refactoring unit-tests for exponential operations

---

heat/core/communication.py
heat/core/devices.py
heat/core/factories.py
heat/core/io.py
heat/core/random.py
heat/core/tests/test_communication.py
heat/core/tests/test_devices.py
heat/core/types.py
scripts/tutorial.ipynb

Resolves issue #263 
Allows to get, set and modify the default communicator for DNDarrays. Adjusted factories to use the default communicator now.

Implemented possibility to set and modify default communicator

---

heat/core/dndarray.py
heat/core/tests/test_dndarray.py

bug was caused by a faulty dtype for the array which received the data from the other processes. debugging this led to the discovery of another bug in getitem: local torch tensors were not being properly type cast. both errors now should be fixed.
Fixes: #329 
- added a dtype to the torch tensor which receives the data from the other process
- added type cast to the local arrays returned by getitem at core of the problem.
Please delete options that are not relevant.
- [X ] Bug fix (non-breaking change which fixes an issue)
Have you handled and tested all split configurations?
yes, standard testing passed. added tests also pass

added dtype to the recv data in balance to allow for 64bit datatypes

---

heat/core/statistics.py
heat/core/tests/test_statistics.py

adds support for ints to mean and variance. The problem was at the pytorch level, the solution was to cast the array to a float. all tests run without failure
Fixes: #349 (and parallel problem with var although it was not previously pointed out)
- casting of the torch tensor to float in the non-distributed case for both mean and var (has no effect if the tensor is already a float)
Have you handled and tested all split configurations?
Yes

added mean support for ints on local level, also a correctness test

---

README.md
doc/source/installation.rst

There are several options for installing HeAT, depending on the needs. These are
documented in the README.md and generated documentation now.
Fixes #335
- Documentation update for installation options
Please delete options that are not relevant.

Document installation options

---

heat/core/communication.py
heat/core/dndarray.py
heat/core/manipulations.py
heat/core/tests/test_communication.py
heat/core/tests/test_dndarray.py
heat/core/tests/test_manipulations.py

Related to #341
Fixes Wrapper for MPI AllToAll
Before, alltoall was treated as a _scatter_like function, with the corresponding buffer preparation. However, due to the fact that AllToAll does send only specific blocks of data to the individual ranks, the strides in the send and receive buffer preparation via Create_Vector did lead to 'scrambled' tensors for non-continuous data, especially in the case when the split axis dimension does not distribute equally over all ranks. 
This PR proposes individual buffer preparations and receive buffer, that creates n=number of processes custom data types for the send buffer , according to the count distribution along the new split axis, that guaranties a specific stride vector wrapping for the receiving buffer.
If either the send or the receive …

All to all mpi type buffer prep

---

heat/core/manipulations.py
heat/core/tests/test_manipulations.py

Added support for vstack and hstack (both are just extensions of concatenate with some allowances for vectors.
Fixes: #27 #172 
- add hstack
- add vstack
Please delete options that are not relevant.
- [x ] New feature (non-breaking change which adds functionality)
- [x ] This change requires a documentation update
Have you handled and tested all split configurations?
Not all specifics tested in the specific tests for h/vstack. tests for these function are to ensure that they behave as intended. all of the foundational elements for these two are handled in concatenate.

added support for vstack and hstack

---

setup.py

Apparently, netCDF4 1.5.3 introduced a problem for us causing the 
problems described in #405.
fixes #405
Limit netCDF4 version to at most 1.5.2
Fixes: #405 
[x] Bug fix (non-breaking change which fixes an issue)
[ ] New feature (non-breaking change which adds functionality)
[ ] yes [x] no
[ ] yes [x] no
[ ] yes [x] no
[ ] yes [x] no

Limit netCDF4 version to at most 1.5.2

---

heat/core/manipulations.py

The sort function used a torch functionality that produces a warning. Torch proposed a different way which was now implemented.
Fixes: #381
- using clone and detach instead of creating a new tensor
[x] Bug fix (non-breaking change which fixes an issue)
[x] yes [ ] no
[ ] yes [x] no
[ ] yes [x] no
[ ] yes [x] no

changed sort to not produce warnings

---

heat/ml/cluster/kmeans.py

In heat.ml.cluster.KMeans._initialize_cluster_centers():
Bcast(xi, root=proc) was failing because `xi.dtype` was initialized as default (float32). However, if `X.dtype = float64`, xi.dtype is float64 as well, hence the memory allocation mismatch.
Fixes: #407 
- Define `xi = ht.zeros(X.shape[1], dtype=X.dtype)`
[x] Bug fix (non-breaking change which fixes an issue)
[ ] New feature (non-breaking change which adds functionality)
[ x] yes [ ] no
[ ] yes [x ] no
Does this change modify the …

Fixes issue #407. Initializing xi to same data type as X.

---

.travis.yml
heat/core/tests/Dockerfile

After some searching around I found [this thread](https://github.com/open-mpi/ompi/issues/4948)  about the problem with the erros in the travis log:
```
Read -1, expected <someNumber>, errno =1
Read -1, expected <someNumber>, errno =1
Read -1, expected <someNumber>, errno =1
Read -1, expected <someNumber>, errno =1
Read -1, expected <someNumber>, errno =1
...
```
Trying out some of the proposed fixes, I finally found one that is actually working in our case.
Maybe someone of you knows more about what I am disabling by this option but as far as I understood it, docker has some security settings which result in this error messages. 
Another approach would be turning of these settings (as described [here](https://github.com/open-mpi/ompi/issues/4948#issuecomment-512987494)), which would …

Travis errno fix

---

heat/core/manipulations.py
heat/core/tests/test_manipulations.py

This PR targets issue #242.
The returned array of `diag()` in case of creating a diagonal array, will be split the same as the input array (`split=None` or `split=0`).
[x] yes - [ ] no
[ ] yes [x] no
[ ] yes [x] no
[ ] yes [x] no

diag() and diagonal() feature

---

heat/core/tests/test_logical.py

bugfix for outdated tests because the pytorch function torch.logical_xor now allows more datatypes.

remove outdated tests for logical_xor

---

CHANGELOG.md
heat/core/regression/lasso/tests/test_lasso.py

Fixes the tests in test_lasso.py such that it completes on GPU.
Issue/s resolved: #462 
- adding device parameters
- numpy() -> cpu().numpy()
no

fix lasso tests on GPU

---

CHANGELOG.md
heat/core/factories.py
heat/core/tests/test_manipulations.py

Fixed Typecasting if factories.array is handed a different dtype than the obj.dtype is
Issue/s resolved: #477
- Addidtion to factories.array function
- [x ] Multiple dtypes tested in relavent functions
no

Typecastion Bugfix

---

CHANGELOG.md
heat/core/communication.py
heat/core/types.py

Added support for CUDA-aware MPI for the other three supporting MPI platforms - MVAPICH, MPICH and ParaStationMPI.
NOTE: if your MPI installation is compiled with CUDA-aware MPI support it may still not use it by default. For most of them a specific environment variable needs to be set our code checks for.
Issue/s resolved: #438
no

Added CUDA-aware MPI support detection for MVAPICH, MPICH and ParaStationMPI

---

CHANGELOG.md
heat/core/random.py
heat/core/tests/test_communication.py
heat/core/tests/test_manipulations.py
heat/core/tests/test_random.py
heat/core/tests/test_statistics.py
heat/regression/lasso/tests/test_lasso.py

All factories, including random now use ht.float32 as default dtype.
Issue/s resolved: #491
no

float32 are now consistent default data types in factories

---

CHANGELOG.md
heat/core/manipulations.py
heat/core/tests/test_manipulations.py

Checks for consistency of comms in the concatenate function and passes them to the result DNDarray.
Issue/s resolved: #422
- Comms must be identical, enforced via RuntimeException
- Operands comm off arr0 is passed to result DNDarray
no

Consistent comms for concatenate

---

CHANGELOG.md
heat/core/dndarray.py
heat/core/linalg/basics.py
heat/core/linalg/qr.py
heat/core/tests/test_tiling.py
heat/core/tiling.py

Removal of the tiling object from the DNDarray
Issue/s resolved: N/A
- removal of tiling object from DNDarray
- minor changes to calls of QR
- doc updates
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
breaking changes have been addressed in codebase
yes, qr functions

Tiles to sep class

---

examples/lasso/demo.py
heat/regression/lasso.py
heat/regression/tests/test_lasso.py

This PR removes PyTorch and Numpy examples from example/lasso/demo.py
Issue/s resolved: #528
Removed PyTorch and Numpy Lasso examples
no

lasso examples

---

CHANGELOG.md
heat/core/arithmetics.py
heat/core/dndarray.py
heat/core/indexing.py
heat/core/linalg/qr.py
heat/core/manipulations.py
heat/core/memory.py
heat/core/tests/test_arithmetics.py
heat/core/tiling.py
setup.py

Changes done to allow for the use of the most recent pytorch release (1.5.0) see changes proposed for more detail
Issue/s resolved: None
- `memory.sanitize_memory_layout` now assumes that the data is distributed in the default way, also it will not change anything if the tensor passed to the function has no elements.
- `DNDarray.redistribute` uses where instead of nonzero (the usage of nonzero there was depreciated)
Compatibility with dependency update
yes, anything which uses

minor tweaks to allow for torch 1.5 compatability

---

CHANGELOG.md
examples/lasso/demo.py
heat/core/base.py
heat/core/dndarray.py
heat/core/io.py
heat/core/statistics.py
heat/core/tests/test_factories.py

Bug fix for issue #566 a raise was removed to allow for the setting of an array in the form of  `x[i] = y` where both `x` and `y` are multidimensional and both are split. The raise was removed entirely because the object `x[i]` is created during runtime and not previously, thus the split axis tested at the beginning of the setitem routing had the split of `x` and not `x[i]`. to determine the split of `x[i]` requires significant overhead (using getitem routine). if the splits do not match a Runtime error will be raised as the local shapes of the PyTorch tensors will not match. A note is made in the docs.
Issue/s resolved: #566 
- removal of the raise in setitem for differening split axes
yes, anything which uses …

removed raise in setitem for differening split axis

---

CHANGELOG.md
heat/core/linalg/basics.py
heat/core/linalg/solver.py

Matmul had a bug for when kB (the inner blocking dimension is 1, when this was the case, it would do a second loop which would re-add previous results to the result array.
matmul of 2 vectors is handled as an early out
in split 10 case for matmul, the remainder handling does not run if kB is equal to 0
Issue/s resolved: #570 
- see description
no

bugfix for matmul bug (split 10)

---

CHANGELOG.md
heat/core/dndarray.py
heat/core/indexing.py
heat/core/linalg/basics.py
heat/core/linalg/solver.py
heat/core/manipulations.py
heat/core/operations.py
heat/core/statistics.py
heat/core/tests/test_dndarray.py
heat/core/tiling.py
heat/naive_bayes/gaussianNB.py
heat/regression/lasso.py

Add method ndim to dndarray for NumPy-API-compatibility. Will replaces numdims()
Issue/s resolved: None
- additional DNDarray method ndim
- deprecation warning on numdims
- replace function calls
New feature
no

feature ndim

---

CHANGELOG.md
heat/core/manipulations.py

In reshape a wrong variable is used at one point.
Issue/s resolved: None
- correction of the array name
Bug fix
no

bug variable name in reshape

---

CHANGELOG.md
heat/core/tests/test_trigonometrics.py
heat/core/trigonometrics.py
setup.py

Issue/s resolved: #546 
This PR adds a arctan2 function to HeAT
- arctan2 function
New feature
no

Feature arctan2

---

CHANGELOG.md
heat/core/dndarray.py
heat/core/tests/test_dndarray.py

Issue/s resolved: #579 
Implentation of tolist() method for DNDarray class. Returns a copy of the DNDarray as a python list.
- add tolist method in dndarray
- new feature
no

tolist() implementation

---

CHANGELOG.md
heat/core/manipulations.py
heat/core/tests/test_manipulations.py

Analog to our DNDarray method `shape` and to `numpy.shape()`
Issue/s resolved: #549 
- Added function manipulations.shape()
- Added tests
- Updated changelog.
no

ht.shape() 

---

CHANGELOG.md
heat/core/tests/test_exponential.py
heat/core/tests/test_rounding.py
heat/core/tests/test_suites/basic_test.py
heat/core/tests/test_suites/test_basic_test.py
heat/core/tests/test_trigonometrics.py
heat/core/tests/test_types.py
heat/core/types.py
heat/spatial/tests/test_distances.py

The dtype comparison was removed as the basic tests works with numpy, which does safe casting instead of intuitive casting. other changes were adjustments for types
Issue/s resolved: 
- change from safe casting to intuitive casting (this come with the possibility of loss during the conversion)
-
-
-
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
no

Changed to intuitive casting, removed dtype tests from basic test class

---

CHANGELOG.md
heat/core/dndarray.py
heat/core/manipulations.py
heat/core/tests/test_manipulations.py

Issue/s resolved: #555 
Introduces rot90. Rotate an array on a specified plane. May change the split axis if it is in the rotation plane similar to transpose.
- add rot90()
New feature
no

Features rot90

---

CHANGELOG.md
heat/core/printing.py
heat/core/tests/test_printing.py

added balance to printing to allow for unbalanced arrays to be printed. 
Issue/s resolved: #617 
- balance added to print
no

added balance to printing._torch_data for printing of unbalanced arrays

---

CHANGELOG.md
heat/cluster/spectral.py
heat/core/dndarray.py
heat/core/linalg/solver.py
heat/core/statistics.py
heat/core/tests/test_dndarray.py
heat/core/tests/test_statistics.py
heat/spatial/distance.py
setup.py

Added `skew()` and `kurtosis()` functions. Also fixed the spectral bug (hopefully)
Issue/s resolved: #98 
- implement `skew()`
- implement `kurtosis()`
- changed `np.inf` to max dtype value in `heat.spatial.distance._quadratic_expand` to avoid issues with MKL backend
-
yes, `cdist` with the use of `_quadratic_expand` will not return infinite values now.

Features/98 moments - skew and kurtosis

---

CHANGELOG.md
heat/core/tests/test_trigonometrics.py
heat/core/trigonometrics.py

aliases added, tests rearranged into alphabetic order in test_trigonmetrics
Issue/s resolved: #628 
- added aliases for arctan -> atan, arctan2 -> atan2, arccos -> acos, arcsin -> asin
- ordered tests in test_trig...
no

added aliases for arc___ functions

---

CHANGELOG.md
heat/core/dndarray.py

Update to slicing with DNDarrays
Issue/s resolved: n/a
- resplit to split None if the key given to the DNDarray getitem is itself a DNDarray
yes, possibly. If a function was working with unbalanced DNDarrays then this slicing scheme would cause issues

added resplit to None for slicing with DNDarrays

---

CHANGELOG.md
heat/core/linalg/basics.py
heat/core/printing.py
heat/core/statistics.py
heat/core/tests/test_statistics.py

Fixed tensor printing issues with torch 1.6.0
Issue/s resolved: #647
- Torch 1.6.0 switches the order of two parameters, respective version check implemented and call-through with corresponding parameter order
no

Fixed torch 1.6.0 printing

---

CHANGELOG.md
heat/cluster/tests/test_kmedoids.py
heat/cluster/tests/test_spectral.py
heat/core/_operations.py
heat/core/dndarray.py
heat/core/manipulations.py
heat/core/printing.py
heat/core/statistics.py
heat/core/tests/test_dndarray.py
heat/core/tests/test_io.py
heat/core/tests/test_statistics.py
heat/core/tests/test_tiling.py
heat/core/tiling.py
setup.py

Update the unittests for argmax and argmin for the changed return behaviour (numpy like) resulting from changes in pytorch 1.6.0 (torch.max, torch.min return first value).
Additionally, mpi_argmax and mpi_argmin sort the inputs by starting index beforehand. Some MPI implementations do not bind the first input to the lower process.
- argmax test update
- argmin test update
- requires torch 1.6.0
- sort arguments in mpi_argmax, mpi_argmin (Fix bug in some MPI implementations)
- updated gpu calls in a few tests (see code for details)
- io tests use the current working directory for the tests instead of a temp directory
Unknown

Updates for pytorch 1.6.0

---

CHANGELOG.md
heat/core/communication.py

Replaced return NotImplemented with raise NotImplementedError
Issue/s resolved: #650 
no

Replaced NotImplemented with NotImplementedError

---

README.md

The installation command contained spaces, which at least my pip didn't like.
no

Fixed install command in readme

---

CHANGELOG.md
heat/core/manipulations.py
heat/core/tests/test_manipulations.py

Renaming of the `axis` parameter and additional hint that it only works on split DNDarrays. 
Issue/s resolved: #665 
- rename `axis` to `new_split`
- add further description
no

Enhancement reshape rename axis to new_split and add description

---

CHANGELOG.md
heat/core/random.py
heat/core/tests/test_random.py

adding random functions and aliases
Issue/s resolved: #553 
- random.random
- random.random_sample
- random.sample
- random.ranf
- random.random_integer
New Feature
no

add random_sample and aliases

---

CHANGELOG.md
heat/core/arithmetics.py
heat/core/manipulations.py
heat/core/random.py
heat/core/tests/test_arithmetics.py
heat/core/tests/test_manipulations.py
heat/core/tests/test_random.py

This one is self-explanatory, see https://numpy.org/doc/stable/reference/generated/numpy.diff.html
Issue/s resolved: none, needed in ASSET
- kwargs prepend, append for ht.diff(), can be scalars or DNDarrays 
no

Add prepend-append functionality to diff()

---

CHANGELOG.md
heat/core/arithmetics.py
heat/core/communication.py
heat/core/dndarray.py
heat/core/linalg/basics.py
heat/core/linalg/qr.py
heat/core/manipulations.py
heat/core/tests/test_communication.py

Removes the `wait` method of `MPIRequest` such that it does not interfere with the lowercase non-blocking MPI functions of mpi4py.
Issue/s resolved: #671 
- delete MPIRequest.wait()
- fix calls using wait() to Wait()
- Bug fix
- Breaking change
no

remove MPIRequest.wait()

---

CHANGELOG.md
heat/core/manipulations.py
heat/core/tests/test_manipulations.py

Fixes the reshape bug on booleans and on floats in some cases. Some tensors were using the dtype of the input by mistake. 
Issue/s resolved: #682 
Issue/s resolved: #654
- fix reshape on booleans
Bug fix
no

fix reshape boolean bug

---

CHANGELOG.md
heat/core/_operations.py
heat/core/devices.py
heat/core/dndarray.py
heat/core/factories.py
heat/core/io.py
heat/core/logical.py
heat/core/manipulations.py
heat/core/random.py
heat/core/tests/test_exponential.py
heat/core/tests/test_manipulations.py
heat/core/tests/test_suites/basic_test.py
heat/core/tests/test_suites/test_basic_test.py
heat/naive_bayes/tests/test_gaussiannb.py

Refines the same device check on array initialization and also fixes the calling functions that it will not be called any longer. Kept as an assertion instead.
Lowers coverage
Issue/s resolved: #675 
- Refine the device check in DNDarray.\_\_init\_\_ and change it into an assertion
- get right device in factories.array
- remove the device id in `devices.cpu.torch_device` to be akin to str(torch.device)
- add "cuda" in devices.\_\_device_mapping allowing to pass `torch.device.type` to `devices.sanitize.device`
- various changes on functions creating instances of DNDarray directly
Bug fix
no

Bug fix / Enhancement array initialization different devices

---

doc/source/tutorial_clustering.rst

Changes the clustering example of the documentation to compile.
- Introduce variable R for radius of the circle
- Use triple string
Doc update. Seems to be not included in changelog so far
no
skip ci

Fix clustering example not compilable

---

CHANGELOG.md
heat/core/linalg/basics.py
heat/core/linalg/tests/test_basics.py

fixes bug by casting tensors to floats before mm operation
Issue/s resolved: #657 
- for `matmul`: cast tensors to floats if the devices are GPUs and the dtypes are ints
no

mm checks and correct int dtypes if A is on the gpu

---

CHANGELOG.md
README.md

Add pointer to stackoverflow forum discussing pyheat.
Issue/s resolved: #700 
- Pointer in README.md
- The change should also go in the documentation, which is on a separate branch at the moment.
no
skip ci

700 support channels

---

CHANGELOG.md
heat/core/dndarray.py

Issue/s resolved: #705 
- both `__getitem__` and `__setitem__` work on copy of `key` if possible (i.e. if `key` is not a tuple)
no

Do not modify key in place within setitem, getitem

---

CHANGELOG.md
README.md
heat/core/factories.py
heat/core/tests/test_factories.py

Issue/s resolved: #691 
ht.asarray() function added. It is a shortcut for array() with copy set to False.  
Some lines in array() are added such that the input array will be directly returned if there is no change. Also, the underlying data of numpy arrays / torch tensors will be reused if copy is False.
- asarray()
- Modification of array() functionality when copy is false 
- New feature
array()

asarray() implementation

---

CHANGELOG.md
setup.py

On the GPU Cluster, setup.py uses the wrong encoding when reading README.md which contains umlauts. This PR sets it explicitly to UTF-8.
- explicit encoding in setup.py
Bug fix
no

[Bug] Set explicit encoding in setup.py

---

heat/core/linalg/solver.py

Reverted inplace calculation from commit 80577f70cf7c91822569288817296bfd858cff73, because this was causing incorrect eigenvalue calculations
Spectral clustering was yielding negative Eigenvalues, which cannot be due to the Laplacian being a positive semidefinite matrix. It turns out that a change in the solver class to inplace operations for updating the w vector caused wrong calculations. 
-```w -= alpha * vi - beta * V[:, i - 1]``` -->  ``` w = w - alpha * vi - beta * V[:, i - 1]``` 
Bug fix (non-breaking change which fixes an issue)
no

Lanczos Bugfix in Solver

---

CHANGELOG.md
heat/core/relational.py
heat/core/tests/test_relational.py
setup.py

Cast the returned arrays in relational functions to bool.
Issue/s resolved: #729 
- Check and cast array returned by all relational functions to bool if necessary
no

relational functions cast to boolean

---

CHANGELOG.md
heat/core/_operations.py
setup.py

Fix distributed local_op with out != None for empty local arrays.
Issue resolved: #731 
- set multiples to zero if division by zero occurs
no

fix local_op + out distributed

---

CHANGELOG.md
README.md
setup.py

This set of changes incorporates updates to README.md and setup.py.
Issue/s resolved: #733 
- Set Development Status :: 4 - Beta in setup.yp
- Update link to CI results and distinguish CPU and GPU tests.
no
skip ci

733 development status

---

CHANGELOG.md
heat/core/dndarray.py
heat/core/tests/test_dndarray.py

This PR fixes the wrong output of `DNDarray.__repr__()` introduced in e88a489e4980e35632b7f2aed503025e3887aad5
Issue/s resolved: #762 
- fix __repr__
no

restore repr

---

CHANGELOG.md
heat/core/arithmetics.py
heat/core/tests/test_arithmetics.py
heat/core/trigonometrics.py

implement unary positive and negative operations + fix deg2rad / rad2deg
Issue/s resolved: #763 
- add unary +
- add unary -
- deg2rad: replace with pytorch function
- rad2deg: replace with pytorch function
- add documentation for alias functions in arithmetics.py
no

add unary negative / positive + fix deg2rad / rad2deg

---

CHANGELOG.md
heat/core/communication.py
heat/core/manipulations.py
heat/core/tests/test_dndarray.py

Removed `storage_offset` when finding the mpi buffer (`communication. MPICommunication.as_mpi_memory()`).
Added allowance for 1 dimensional non-contiguous local tensors in `communication. MPICommunication.mpi_type_and_elements_of()`
Issue/s resolved: #769 #784 
- removed `storage_offset` addition to data pointer in `communication. MPICommunication.as_mpi_memory()`
- added if block to determine strides for non-contiguous 1D local tensors in `communication. MPICommunication.mpi_type_and_elements_of()`
no

Change MPI buffer creation + 1D non-contiguous tensors

---

CHANGELOG.md
heat/core/dndarray.py

a minor bug was showing up where the `bcast` operation was not putting the data onto the proper GPU in the `__getitem__` function. the code added may not be hit all the time, but it is safeguard for when this may happen. 
Issue/s resolved: n/a
- move the local array to the proper GPU after the `bcast` when there are integers in the getitem key
no

added device call after the bcast in the getitem

---

doc/source/conf.py
doc/source/tutorial_30_minutes.rst
doc/source/tutorials.rst

A small PR that adds the [copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/) extension for sphinx in the docs. Like the its name suggests, it adds a button at the side of an code block and copies the text to the Clipboard when clicked. Some configuration was done for stripping command prompts and outputs.
Small text change in the tutorials main page to stick to the heat theme + typo fix.
Issue/s resolved: #n/a
- docs: copybutton extension
- docs: text rewrite
skip ci

docs copybutton

---

CHANGELOG.md
heat/classification/tests/test_knn.py
heat/core/io.py
heat/core/tests/test_io.py
heat/utils/data/tests/test_partial_dataset.py

Fixes an import error in io.py when optional dependencies are not available and changes error message when saving or loading a file that requires an optional dependency.
Issue resolved: #786 
Issue resolved: #697 
- remove save_hdf5 from general _all_
- skip tests using optional dependencies if not available
- more descriptive error message for files that need an optional dependency.
no

IO import issues

---

CHANGELOG.md
heat/core/factories.py
heat/core/tests/test_factories.py

Implements meshgrid functionality to Heat. It uses the pytorch function of the same name. That function does not support the indexing parameter. As a hotfix for now, the first and second vector are switched during computation when using 'xy'. If the split is on the first or second axis, they are resplitted beforehand.
Issue/s resolved: #775 
- add meshgrid function
- New feature
no

meshgrid implementation

---

CHANGELOG.md
heat/core/linalg/basics.py
heat/core/random.py

`dot` can multiply matrices and vectors now
`randn` bug is now hopefully fixed. tested up to memory limit of my personal machine
Issue/s resolved: #817 #819 
- `dot` uses matmul to handle `matrix @ vector` inputs
- inputs to kundu transform in `randn` get a very small offset to move them away from 0. this should avoid the `inf` values from showing up without changing the distribution very much at all
no

Dot product matrix vector ops + randn inf bugfix

---

CHANGELOG.md
README.md
heat/core/manipulations.py
heat/core/tests/test_manipulations.py

Implementation of moveaxis that calls transpose internally for computation.
Issue/s resolved: #848 
- add moveaxis
- New Feature
no

add moveaxis

---

CHANGELOG.md
heat/core/manipulations.py
heat/core/tests/test_manipulations.py

Adds swapaxes. It is mostly an alias function for transpose on two axes.
Issue/s resolved: #849 
- add swapaxes
no

add swapaxes

---

CHANGELOG.md
heat/core/_operations.py
heat/core/linalg/basics.py
heat/core/linalg/solver.py
heat/core/linalg/tests/test_basics.py

Rewrite of norm to support more types of norms.
Issue/s resolved: #836 #845 #847 
- add norm, vector_norm, matrix_norm
- fix bug reduce_op with axis and keepdim
- dot returns a 0-dim array instead of builtin float
- fix bug in max/min (_reduce_op) on distributed arrays.
- New feature
- Bug fix
no

norm implementation

---

CHANGELOG.md
heat/core/dndarray.py
setup.py

Current `torchvision` version 0.10 requires PyTorch 1.9, which we are not supporting with Heat 1.1.x.
- Constraining `torchvision<0.10` to match the supported `pytorch` version range.
- Bug fix (non-breaking change which fixes an issue) 
- 
no

torchvision version range compatibility with pytorch version

---

CHANGELOG.md
heat/core/random.py
heat/core/tests/test_random.py

Convenient function to draw samples from a generic normal distribution. 
Issue/s resolved: #855
- normal
- standard_normal
- New feature
no

add normal, standard_normal

---

CHANGELOG.md
heat/core/logical.py
heat/core/tests/test_logical.py

Implementation of `signbit`
Issue/s resolved: #861 
- signbit
- New feature
no

add signbit

---

CHANGELOG.md
heat/core/complex_math.py
heat/core/tests/test_complex_math.py

Adds `conj` to `DNDarray` to match the NumPy/PyTorch API
- DNDarray method `conj`
- Enhancement/feature
N/A :smiley: 
N/A :smiley: 
no

conjugate method in DNDarray

---

heat/core/_operations.py
heat/core/stride_tricks.py
heat/core/tests/test_arithmetics.py
heat/core/tests/test_statistics.py
heat/core/types.py

Debugging GPU tests on #902. Work in progress.
Issue/s resolved: #891
- `stride_tricks.broadcast_shape` to call `torch.broadcast_shapes`, not `np.broadcast_shapes`
-
-
-
yes / no

Debugging branch for #902

---

CHANGELOG.md
heat/core/random.py
heat/core/tests/test_random.py

Issue/s resolved: #913 
- allow ints for size in randint
- Bug fix
n/a
n/a
no

`randint` accept ints for 'size'

---

doc/source/getting_started.rst

Changed Validation section.
Issue/s resolved: #955 

changed documentation small fix

---

CHANGELOG.md
heat/core/random.py

Replaced factories.array with DNDarray in random.py
Issue/s resolved: #800 
- factories.array -> dndarray.DNDarray
enhancement
no

Random: Replaced factories.array with DNDarray

---

CHANGELOG.md
heat/core/communication.py

Expanding on #940, not only `MPI.COMM_WORLD` but also `MPI_SELF` must be duplicated 
Issue/s resolved: #895
- duplicate `MPI_SELF`
-
-
-
no

Duplicate MPI_SELF as well

---

heat/core/factories.py
heat/core/tests/test_factories.py

Allow `linspace` to be called with 0 sample size. This also fixes an inconsistency with the documentation, which already allows `num` to be non-negative.
Issue/s resolved: #994
no
skip ci

Non-negative sample size for `linspace`/`logspace`

---

heat/core/tests/test_types.py
heat/core/types.py

Reads the minimum value of a data type directly from the return values of pytorch `iinfo` and `finfo` functions. This is superior to the old method of calculating the minimum value from the maximum value as the minimum value is calculated differently for different data types (e.g. `min = -(max + 1)` works for signed integers but not unsigned integers).
Issue/s resolved: #996
no
skip ci

Bug/996 `iinfo`/`finfo` `min` value

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci_cpu.yml
.gitlab-ci.yml
README.md
codecov.yml
setup.py

Mirrors the repository to HZDR's GitHub instance and runs the CI there.

Mirror Repository and run GitHub CI at HZDR

---

heat/core/random.py
heat/core/tests/test_random.py

_**Copied over from issue 1076**_
Apparently, torch has some precision problems during division. The division operation, that takes place when the number of elements in each process is calculated, causes some problem.
**Code:**
```
import torch
print(f"Number of elements in tensor: 6667*3523={23487841}")
print(23487841/3523)
print(torch.tensor(23487841)/3523)
```
**Output:**
```
Number of elements in tensor: 6667*3523=23487841
6667.0
tensor(6666.9995)
```
This small precision error is blown up when the number of elements is huge. That's probably why the tests did not catch the bug because the number of elements were small enough.
Issue/s resolved: #1076 
Bug fix
no

Fix division precision error in `random` module

---

heat/nn/data_parallel.py

Black and Pydocstyle have conflicting requirements of code style. Probably due to the [new release of black](https://black.readthedocs.io/en/stable/change_log.html#id3). Found a work-around in [this comment](https://www.github.com/PyCQA/pydocstyle/issues/361#issuecomment-834166047). 
black wants an empty line before the internal function. pydocstyle does not want an empty line after docstring.

Work-around for pre-commit ci failure

---

heat/core/signal.py

Issue resolved: #1085 
Convolve is not working with multiple gpus with distributed kernel.
- bcast --> Bcast
- Bug fix 
no

Fix #1085: Convolve with distributed kernel on multiple GPUs

---

.github/workflows/CommentPR.yml
.github/workflows/ReceivePR.yml
.github/workflows/ci_cb.yml
.gitlab-ci.yml
README.md

Adds workflows that get activated when a new PR is created. Runs a unit test on a single process and returns a message on success. The local PR branch is then send to the mirrored repository.
Pushes on the main and release branches are mirrored only to avoid double testing of branches/PR on the upstream repository.
Issue/s resolved: #1113 
- add workflows for PRs
- update existing workflow for mirroring
- workflow update

add workflows for PRs

---

.github/PULL_REQUEST_TEMPLATE.md
.github/release-drafter.yml
.github/workflows/ci.yaml
.github/workflows/codesee-arch-diagram.yml
.github/workflows/scorecard.yml
heat/__init__.py
heat/core/_operations.py
heat/core/communication.py
heat/core/devices.py
heat/core/signal.py
heat/core/tests/test_signal.py
heat/sparse/__init__.py
heat/sparse/_operations.py
heat/sparse/arithmetics.py
heat/sparse/dcsr_matrix.py
heat/sparse/manipulations.py
heat/sparse/tests/__init__.py
scripts/heat_dev.yml
scripts/heat_env.yml
scripts/heat_test.py

Issue/s resolved: suboptimal merge result of the latest `release/1.2.x` into `main` 
- entire branch should be at [a5515f0850](https://github.com/helmholtz-analytics/heat/tree/a5515f08501388f95b571eb28e604d88a7dc86c4/heat) level, including new CI
- bug fixes and new pytorch workflow from `release` branch merged into `main`
-
-
NA
Na
no

Fix `main` after merging `release/1.2.x`

---

heat/core/dndarray.py
heat/core/tests/test_dndarray.py

This method returns **a view** of the underlying process-local array as numpy ndarray. If the DNDarray is on GPU, the array is copied to CPU first.
With this change, passing a DNDarray to `np.asarray()` returns a valid np.ndarray. This is needed for interoperability with other libraries in the numpy ecosystem.
Basic example with `xarray`:
```
>>> import xarray as xr
>>> import heat as ht
>>> a = ht.arange(10).reshape(5,2)
>>> a
DNDarray([[0, 1],
[2, 3],
[4, 5],
[6, 7],
[8, 9]], dtype=ht.int32, device=cpu:0, split=None)
>>> xr_a = xr.DataArray(a)
>>> xr_a
<xarray.DataArray (dim_0: 5, dim_1: 2)>
array([[0, 1],
[2, 3],
[4, 5],
[6, 7],
[8, 9]], dtype=int32)
Dimensions without coordinates: dim_0, dim_1
```
If the DNDarray is distributed, the example above will return an xarray of the local …

Introduce `DNDarray.__array__()` method

---

.github/workflows/CIBase.yml
.github/workflows/CommentPR.yml
.github/workflows/ReceivePR.yml
heat/core/linalg/tests/test_qr.py
heat/core/tests/test_statistics.py

This Pull Request skips some tests such that it can be run on AMD GPU. Additionally branches starting with 'support/' are tested on push events.
Issue/s resolved: #694
- skip tests using special cuda libraries
- push trigger event on support branch
- testing
yes / no

support amd HIP

---

heat/core/linalg/svdtools.py
heat/core/linalg/tests/test_svdtools.py

A proposal to reduce communication in #1126 
- for every iteration, add a row to `U_loc` and store `err_square_loc` in it.
- communicate `U_loc` and `err_square_loc` in one single MPI call instead of one each
- separate tensors again after communication
-
New feature 
NA
no

hSVD: Concatenate arrays to reduce communication

---

README.md

Updated the README file In the ```release/1.2.x``` branch, by adding links to both the [stable](https://heat.readthedocs.io/en/stable/) and [latest](https://heat.readthedocs.io/en/latest/) versions of the docs.
Issue/s resolved: #1101
No.

Fixed the ReadTheDocs link on ```release/1.2.x``` branch

---

.readthedocs.yaml

- General:
This Pull Request introduces a configuration file which is now required for Read the Docs.
Issue/s resolved: #1185 
- add `.readthedocs.yaml`
no

Create configuration file for Read the Docs

---

.github/issue-branch.yml
quick_start.md

- General:
Small fixes to automated branch creation on Issue assignment. 
Issue/s resolved: #1182 
- introduced `workflows` prefix
- modified branch naming scheme to match what we used so far
- updated Quick_start.md accordingly
-
NA
NA
no

Small fixes to automated branch creation on Issue assignment

---

README.md

- General:
Hi @JuanPedroGHM , I propose to display the badges in order of importance to the users. ~~I've also updated some labels so that their meaning is more obvious.~~ EDIT: ok, I see that changing the labels doesn't make the tiniest difference. What do you think?
-
-
-
-
NA
NA
no

Reorganize badges order and labels on repo landing page

---

heat/cluster/tests/test_spectral.py

see #655 for the bug that cannot be reproduced anymore

Remove restriction to < 7 processes in `test_spectral.py`

---

.perun.ini
benchmarks/cb/cluster.py
benchmarks/cb/linalg.py
benchmarks/cb/main.py
benchmarks/cb/manipulations.py

Includes the changes done #1158, and includes updates to accommodate the new version of perun. Created a new branch and pull request because I messed up while rebasing.
* Removed data generation from the benchmarked functions.
* Updated perun api.
* Seed fixed in main script
* Device can be set with ENV variables
Issue/s resolved: #1157 
no

Separate data and computation in benchmarks

---

.gitignore
heat/utils/data/matrixgallery.py
heat/utils/data/tests/test_matrixgallery.py

- General:
Creating a new PR to add tests for the Hermitian test matrix implemented in #1086.
Workflow: 
- merge #1086 into this PR ✅ 
- merge this PR into main
Issue/s resolved: #1073 
-
-
-
-
no

Add `hermitian()` to matrix gallery

---

heat/core/dndarray.py
heat/core/manipulations.py
heat/core/tests/test_dndarray.py
heat/core/tests/test_manipulations.py

- General:
As per title, added the collect method which brings all data of a distributed tensor to a single rank, which can be specified by the user. Uses the redistribute method.
Issue/s resolved: [implement a collect method #480](https://github.com/helmholtz-analytics/heat/issues/480)
no

Introduce `manipulations.collect(target_rank)` function and in-place `DNDarray.collect_(target_rank)` method

---

heat/core/__init__.py
heat/core/stride_tricks.py
heat/core/tests/test_stride_tricks.py

- General:
This PR addresses issue #904  by implementing `ht.broadcast_shapes`to align with numpy and torch counterparts in terms of naming, calling, and handling multiple shapes.
Issue/s resolved: #904 
- Added ht.broadcast_shapes with the desired behavior.
New feature (non-breaking change which adds functionality)
Memory requirements for this change have not been profiled at this time.
Performance metrics for this change have not been measured at this time.
no

Added `ht.broadcast_shapes`

---

benchmarks/cb/manipulations.py

- General:
Issue/s resolved: #1207 
- added concatenation along split axis to `manipulations` benchmarks
-
-
-
NA
NA
no

Add `ht.concatenate` to Continuous Benchmarks

---

heat/core/manipulations.py
heat/sparse/manipulations.py
heat/sparse/tests/test_manipulations.py

worked on [Feature-384 Sparse] to_sparse() method for DNDarray class 
- General:
Implemented `to_sparse()` method for DNDarray class conversion to DCSR_matrix representation
Issue/s resolved: #1054 
- Added the to_sparse() method to the DNDarray class for converting to a DCSR_matrix representation.
New feature (non-breaking change which adds functionality)
Memory requirements for this change have not been profiled at this time.
Performance metrics for this change have not been measured at this time.
no

Implement `to_sparse()` method for DNDarray conversion to DCSR_matrix

---

docker/README.md
quick_start.md

Removed specific version numbers and image tags from docker documentation, to avoid constant changes with each version.

replaced version numbers from docker docs with placeholders

---

.github/workflows/bench_report.yml
.github/workflows/bench_trigger.yml

Misconceptions about some github variables from the pull_request and push events lead to triggering the benchmarks with wrong values. This aims to correct it, while also avoiding to create an endless check that waits for the benchmark to finish.
Issue/s resolved: #1219 
- Small corrections to trigger benchmark action
- Changes to CB actions.

Trigger Benchmark Corrections

---

.github/workflows/bench_trigger.yml

- In bench_trigger.yml
- Sets "main" branch name correctly.
- Does not create unnecessary checkmarks. 
-  Solves #1226

Benchmarks: missing branch argument in gitlab pipeline trigger

---

doc/requirements.txt

- General:
Update the sphinx requirements to the latest versions fixing a build error in readthedocs.
Issue/s resolved: #1233 
- update sphinx requirements
n/a
n/a
no

Update sphinx package requirements

---

doc/source/getting_started.rst
doc/source/tutorial_clustering.rst
doc/source/tutorial_parallel_computation.rst

- General:
Issue resolved: #1235 
To get started with Heat I went through the [documentation](https://heat.readthedocs.io) and particularly the provided [tutorials](https://heat.readthedocs.io/en/stable/tutorials.html). While doing so, I noticed a few minor linguistic mistakes and typos in code snippets, which I correct here. Also I try to slightly improve the uniformity of the given code examples. 
no

Update Heat Tutorials, fix typos.

---

.github/workflows/pytorch-latest-main.yml
.github/workflows/pytorch-latest-release.yml
heat/core/linalg/tests/test_solver.py

- General:
Issue/s resolved: #1241 
- upgrade to the latest version of checkout action
- delete the token parameter such that the default action token is used
no

Fix Pytorch release tracking workflows

---

heat/core/linalg/tests/test_solver.py

- General:
Issue/s resolved: CI matrix stuck for days
- increase tolerance in Lanczos tests for single-precision `allclose` checks. Now applies to all PyTorch versions, not just >=1.13
-
-
-
NA
NA
no

Increase tolerance for `ht.allclose` on `ht.inv` operations for all torch versions

---

.pre-commit-config.yaml

- General:
`.pre-commit-config.yaml` updates are automated on the `main` branch, the corresponding file on `release/1.3.x` has diverged. Bringing it to the latest version.
- pull current `.pre-commit-config.yaml` from `main` 
-
-
-
NA
NA
NA
no

Sync `pre-commit` configuration with `main` branch

---

heat/core/version.py

- General:
- Upgrade to 1.3.1
-
-
-
no

Update version before release 

---

.github/workflows/changelog-updater.yml

- General:
Workflow file got fixed in main, but not in the release branch. 
- Update `.github/workflows/changelog-updater.yml` in release branch with previous changes from main. 
- Workflow changes
no

Update outdated `changelog-updater.yml` workflow

---

CITATION.cff

Names of non-core team members have been added to CITATION.md file to be merged with first bugfix release 1.4.1

added names of non-core members in citation file

---

heat/core/dndarray.py

- General:
Enabling one-sided halo for #1419.
Usage (run on n>1 MPI processes):
```python
a = ht.arange(100, split=0).reshape(10, 10)
a.get_halo(2, prev=False)
print("Test one-sided halo = ", a.array_with_halos)
```
- introduced boolean kwargs `prev` and `next` for `DNDarray.get_halo()`, both True by default
- data communication to next MPI rank only if `prev == True`
- data communication to the previous MPI rank only if `next == True`
no

Support one-sided halo for DNDarrays

---

heat/core/io.py
heat/core/tests/test_statistics.py
setup.py

- General:
Copy-paste from #1536:
`test_io` has been failing since netcdf4 release 1.7.1 with the following error:
```
FAILED heat/core/tests/test_io.py::TestIO::test_load - OSError: [Errno -101] NetCDF: HDF error: '/builds/helmholtz-analytics/ci/heat/heat/datasets/iris.nc'
FAILED heat/core/tests/test_io.py::TestIO::test_load_netcdf - OSError: [Errno -101] NetCDF: HDF error: '/builds/helmholtz-analytics/ci/heat/heat/datasets/iris.nc'
FAILED heat/core/tests/test_io.py::TestIO::test_save - RuntimeError: NetCDF: Problem with HDF5 dimscales.
FAILED heat/core/tests/test_io.py::TestIO::test_save_exception - RuntimeError: NetCDF: Problem with HDF5 dimscales.
FAILED heat/core/tests/test_io.py::TestIO::test_save_netcdf - RuntimeError: NetCDF: Problem with HDF5 dimscales.
```
In …

Address test failures after netCDF4 1.7.1

---

heat/utils/data/datatools.py

- General:
So far, the Heat dataset requires the implementation of an ishuffle method that defines the shuffling of data between epochs. This is not compatible with the PyTorch dataset class. To enable the use of PyTorch dataset classes, ishuffle is now optional.
- New feature
no

Make `dataset.ishuffle` optional 

---

heat/core/signal.py
heat/core/tests/test_signal.py

- General:
This PR expands `ht.signal.convolve` to perform 1-D convolutions on a batch of 1-D arrays, i.e. 
- if `signal.shape = (..., n)` and `kernel.shape = (m,)`:  `signal`'s last dimension will be convolved with `kernel`. 
- if e.g. `signal.shape = (i, j,  n)` and `kernel.shape = (i, j,  m,)`: each element `signal[i, j]` of size `n`  will be convolved with the corresponding element `kernel[i,j]` of size `m`. 
- Signal and kernel can be any number of dimensions, as long as the batch dimensions match.
- Signal and kernel can be distributed along any of the batch dimensions.
Issue/s resolved: #1514 
Related: #1396 
- enable batch 1-D convolution
- expand documentation, examples
- expand tests
-
yes, instead of …

Support batch 1-d convolution in `ht.signal.convolve`

---

heat/core/__init__.py
heat/core/tests/test_vmap.py
heat/core/vmap.py

- General:
Issue/s resolved: #1383 
The implemented vmap-functionality is similar to the one of PyTorch. It allows vectorized application of PyTorch-functions to one or multiple DNDarrays with vectorization taking place along the respective split axes. 
An artificial example, how vmap does work, is found in the tests. 
new feature
no

Distributed `vmap` functionality for vectorization across split dimension 

---

CHANGELOG.md
heat/core/version.py

Changes in documentation, names and other stuff for the new release.

Heat 1.4.2 preparation

---

heat/core/io.py

- General:
Issue/s resolved: #1601 
-
-
-
-
no

`load_npy_from_path`: improve load balancing 

---

heat/cluster/tests/test_batchparallelclustering.py

- General:
Issue/s resolved: #1612 
The problem was that the way how the test had been formulated; it had been checked that labels.min()==0 and labels.max()==n_clusters-1. In very rare cases empty clusters might occur and if this empty cluster got the label 0 or n_clusters-1 the tests failed by construction although there's actually no error. 
Tests have been adapted to  labels.min()>=0 and labels.max()<=n_clusters-1. 
yes / no

Resolve assertion error in tests of Batch-parallel clustering

---

doc/requirements.txt

This fix downgrades the sphinx version back because sphinx_rtd_theme is not compatible with sphinx >= 8
- set sphinx back to 7.4.7
Documentation / Fix

downgrade sphinx version

---

heat/cluster/batchparallelclustering.py
heat/cluster/tests/test_batchparallelclustering.py

- General:
Issue/s resolved: #1592 
- output labels had int32-data type as Heat-arrays, but internally they were int64-floats in torch; this causes problems when going on with computations after clustering. Now, the torch labels are cast to int32; this is no problem as nobody will have more than int32 cluster centers. 
- torch.multinomial used for K-Means++ initialization on each MPI-process has a limit of 2^24 elements (at least on GPU). Thus, if there are more than 2^24 elements to cluster on each process, we now take a uniform subsample before doing K-Means++. 
yes / no

Bugs/1592  Resolved two bugs in BatchParallel Clustering

---

heat/core/linalg/basics.py
heat/core/linalg/tests/test_basics.py

- General:
Issue/s resolved: #1645 
-
-
-
-
yes / no

Raise Error for batched vector inputs on matmul

---

.github/release-drafter.yml

Release drafter action should now be able to distinguish between releases on different branches.
- General:
Add extra option to release-drafter.yml to base the release draft based on the current branch.
- "filter-by-commitish: true" -> I don't think I have ever seen it called commitish

Release drafter action handles multi-branch releases

---

.github/release-drafter.yml

- General:
Missing backported PR to release branch
- Release drafter filters by branch
-
-
-
Release drafter config
yes / no

fix: missing backported pr

---

heat/core/statistics.py
heat/core/tests/test_random.py
heat/utils/data/matrixgallery.py

- General:
`test_random` has been giving us problems in connection to `.numpy()` calls (aka Allgather/Allgatherv and copying to CPU) before. 
As far as I can tell, it isn't any particular instance of "allgathering" that doesn't work. On the AMD runner (2-process GPU tests), since this Monday, `test_random` has been failing consistently around the 10th numpy() call in the module. 
I have refactored `test_random` to gather and copy only when absolutely necessary. It now gathers/copies to CPU only 8 times, as opposed to 47 in the legacy implementation.
Issue/s resolved: #1682 
- remove unnecessary numpy() calls
-
-
-
Bug fix (non-breaking change which fixes an issue) 
NA
NA
no

Refactor `test_random` to minimize collective calls 

---

CHANGELOG.md
CITATION.cff
heat/core/version.py

Update version and list of contributors before releasing 1.5

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/ci.yaml
heat/core/tests/test_random.py
setup.py

- General:
Backport of PR #1655
yes / no

Support PyTorch 2.4.1 (#1655)

---

pyproject.toml
setup.cfg

- General:
This PR adds the bare minimum of changes to the pyproject.toml file that are required in a mordern python project.
Issue/s resolved: #1702 
- specify build-system table
Other
yes / no

Modernise setup.py configuration

---

.pre-commit-config.yaml

- General:
Modifying pre-commit-config to prevent picky formatting of our tutorials. Once this is merged, we can address formatting in #1523 
Issue/s resolved: None
- add directory `tutorials` to `exclude`  field like in #1523  
-
-
-
NA
NA
NA
no

Linters  will no longer format tutorials

---

heat/core/printing.py

- General:
I noticed that printing out moderately large DNDarrays in non-distributed mode (i.e. interactive session or split=None) takes a disproportionate amount of time (see below) compared to printing the underlying tensor. Culprit is the [`Formatter` call](https://github.com/helmholtz-analytics/heat/blob/2fb161843255a145c166c33cbcf9e2065ae86b85/heat/core/printing.py#L310). 
I've changed the printing module to bypass `Formatter` if the input dndarray is not distributed. Torch takes care of the data formatting, tests pass.
Example: 
```
data =  ht.random.randn(91392, 52, 4)
print(data)
```
On 1 process: 
`main` branch: 84 seconds
this PR: 0.01 seconds
- let torch handle formatting of non-distributed data
-
-
-
- Bug fix (non-breaking change which …

Bug fix: printing non-distributed data 

---

heat/core/tests/test_communication.py

So far, the only test of large count MPI actually run on the AMD runner was the test for Isend-Recv on CPU on 4 processes. For whatever reason this often failed. I have run the tests for the communications module (incl. the large scale tests) both on CPU and GPU (2x Nvidia) on our workstation for 2 to 8 processes. No error occurred; thus it is very likely a problem related to the AMD-runner which motivated skipping these tests on the AMD runners.
New version is to run large count Isend-Recv and Allreduce only on the CUDA-runner but on 2 and 3 (both GPU) processes.

Skip large-count communication tests on AMD runner

---

.github/workflows/ReceivePR.yml
.github/workflows/ci.yaml
heat/core/linalg/tests/test_basics.py
heat/core/tests/test_exponential.py
heat/core/tests/test_manipulations.py
heat/fft/tests/test_fft.py
setup.py

- General:
Fixed DeprecationWarnings from numpy 2.x
Issue/s resolved: #1552 
- unittests use vstack instead of row_stack if the numpy version is >= 2.0.0
- unittests now pass axes to np.fft.fftn when s is not None
- changed setup.py to allow numpy versions >= 2.0.0
- changed requirements (python 3.10, numpy 1.23.5, scipy 1.14.0)
- changed workflows to use python 3.10
yes / no

Make unit tests compatible with NumPy 2.x

---

heat/core/dndarray.py
heat/core/linalg/polar.py
heat/core/tests/test_dndarray.py

- General:
Add special methods for NumPy that allows to divert the execution of functions when used on heat arrays.
Issue/s resolved: #1887 
- add `__array_ufunc__` method
- add `__array_function__` method
no

Expand np funcs to heat
