- heat/core/tensor.py
> Issue #60: fix ht.floor docstring to properly print math

- setup.py
Add heat.core, heat.ml, and heat.ml.cluster to the list of packages. Also,
install README.md and LICENSE file. README.md is required by setup.py for the
long_description field.
> Install all packages, not just top level heat

- heat/core/communication.py
- heat/core/tensor.py
- heat/core/tests/test_tensor.py
> Implementation of the .array(...) factory function

- heat/core/operations.py
- heat/core/tensor.py
- heat/core/tests/test_operations.py
> Features/reduceops 

- heat/core/tensor.py
- heat/core/tests/test_tensor.py
> Resolved issue #136, provides implementation for is_distributed() call for tensor

- heat/core/tensor.py
- heat/core/tests/test_trigonometrics.py
- heat/core/trigonometrics.py
> Implementation of tan()

- heat/core/tensor.py
- heat/core/tests/test_tensor.py
> add empty and empty_like

- heat/core/tensor.py
- heat/core/tests/test_tensor.py
> Implements full and full_like

- heat/core/rounding.py
- heat/core/tensor.py
- heat/core/tests/test_rounding.py
> ceil() implementation

- heat/core/__init__.py
- heat/core/constants.py
- heat/core/tests/test_constants.py
- heat/core/tests/test_types.py
Solves #24 , #123 and #132 
- Implementation of Constants inf, nan, pi and e
- No distinction between GPU and CPU:
- pi and e are "hard-coded" as floating precision (in analogy to numpy)
- inf an nan are tunneled from float('inf') and float('nan'), the IEEE 754 of infinity and not a number (should be supported by NVIDIA ABD CUDA9
> 24 implementations of constants

- heat/core/tensor.py
- heat/core/tests/test_trigonometrics.py
- heat/core/trigonometrics.py
> implemented sinh

- heat/core/tensor.py
- heat/core/tests/test_trigonometrics.py
- heat/core/trigonometrics.py
> implemented tanh

- heat/core/arithmetics.py
- heat/core/operations.py
- heat/core/relations.py
- heat/core/rounding.py
- heat/core/tensor.py
See #195.
Changed the indents in al files to be more uniform across the project.
> Fix indents in documentation

- heat/core/arithmetics.py
- heat/core/tensor.py
- heat/core/tests/test_arithmetics.py
> Implemented mod()

- heat/core/tensor.py
- heat/core/tests/test_tensor.py
> eye() feature

- .travis.yml
- heat/core/io.py
- heat/core/tests/test_io.py
- heat/core/tests/test_tensor.py
* loading netcdf data files with empty chunks
* eye() unittests with non-iterable offsets
> Provides bug fixes for: 

- heat/core/dndarray.py
- heat/core/tests/test_dndarray.py
added simple item function for getting the singular element from a 1D tensor (analogous to the pytorch command)
> added item function

- heat/core/__init__.py
- heat/core/dndarray.py
- heat/core/manipulation.py
- heat/core/stride_tricks.py
- heat/core/tests/test_manipulation.py
Resolves issue #258 
* added module-level function
* added docstrings
* added unittests
> expand_dims() implementation

- heat/core/dndarray.py
- heat/core/factories.py
- heat/core/operations.py
- heat/core/tests/test_arithmetics.py
- heat/core/tests/test_factories.py
- heat/core/tests/test_operations.py
- heat/core/tests/test_relational.py
Solves several issues with __binary_op
- operants are now symmetric in case of symmetric operations 
- fixes a error in broadcasting
> Features/277 fix issues with __binary_op

- heat/core/arithmetics.py
- heat/core/factories.py
- heat/core/tests/test_factories.py
Add logspace factory.
Fixes: #237 
logspace in factories calls linspace
Fixes an inconsistency with modulo function in arithmetics.
Please delete options that are not relevant.
> add logspace factory

- heat/core/communication.py
Hotfix for failing build of current master with n=1 process
Fixes: #
- AllToAll for self.size == 1 
- [ x] Bug fix (non-breaking change which fixes an issue)
Have you handled and tested all split configurations?
hope so
> Bugfix AllToAll for single process application

- heat/core/io.py
- heat/core/manipulations.py
- heat/core/statistics.py
- setup.py
Updates to multiple files to allow for use of pytorch 1.3. 
Fixes: #394 
- added dtype specification to index tensors created in sort
- forced `last_line` in load_csv to be an int
- modified `offset` in argmax/argmin to be a tensor, to match the type of `indices`
[X] Bug fix (non-breaking change which fixes an issue)
[X] New feature (non-breaking change which adds functionality)
[X] yes [ ] no
[ ] yes [X] no
[ ] yes [X] no
Are there …
> Features/394 torch1.3 update

- heat/core/dndarray.py
Update on the balance bug, found a bug with >8 processes, adjusted the code to correct the start and stop processes for each process
[X] Bug fix (non-breaking change which fixes an issue)
[ ] New feature (non-breaking change which adds functionality)
[X] yes [ ] no
[ ] yes [X] no
[ ] yes [X] no
[ ] yes [X] no
> fixed issue with the start and stop processes in balance

- heat/core/tests/test_statistics.py
- heat/ml/cluster/tests/test_kmeans.py
- heat/ml/regression/lasso/tests/test_lasso.py
Fixes: #433
- add `if ht.io.supports_hdf5():` before using function in unit tests
[✔] Bug fix (non-breaking change which fixes an issue)
[✘] New feature (non-breaking change which adds functionality)
[✘] Breaking change (fix or feature that would cause existing functionality to not work as expected)
[✘] Documentation update
[ ] yes [✘] no
[ ] yes [✘] no
[ ] yes [✘] no
[ ] yes [✘] no
> check for existing dependency in tests

- heat/core/manipulations.py
@coquelin77 mentioned that there were still some debugging lines left in my code that I removed now. Hope this were the last ones.
[x] Bug fix (non-breaking change which fixes an issue)
[ ] New feature (non-breaking change which adds functionality)
[x] yes [ ] no
[ ] yes [x] no
[ ] yes [x] no
[ ] yes [x] no
> Diag Hotfix

- CHANGELOG.md
- heat/core/version.py
Implement a changelog to prepare for the release of version 0.2.0
- add CHANGELOG.md
New feature (non-breaking change which adds functionality)
> added changelog and added info for version 0.2.0

- heat/spatial/distance.py
- heat/spatial/tests/test_distances.py
Added missing device calls in cdist tests
Issue/s resolved: #485 
- added device parameters
> cdist tests on GPU

- docs/pull_request_template.md
fixed in pull_request_template.md
- relavent -> relevant
> typo pull_request_template.md

- heat/classification/__init__.py
Classification Module needs an init file
> Add __init__.py to classification module

- Jenkinsfile
Add a test with 7 processes
skip ci
> test on multiple processors

- Jenkinsfile
- setup.py
Tests on agent upgrade the required packages to the latest version automatically + tests for 5,6,8 processes
> upgrade packages dependencies in tests + 5,6,8 procs

- codecov.yml
codecov: lowers the percentage in project and adds a threshold for patch
> adjust codecov patch

- CHANGELOG.md
- heat/core/manipulations.py
Amount of `sent` items among processes was not being tracked correctly, so some constellations of items/processes resulted in tests failure. 
- modify `sent` to keep track of items sent to lower-number processes as well
no
> Fix balacing in sort()

- CHANGELOG.md
- heat/core/tests/test_trigonometrics.py
- heat/core/trigonometrics.py
Add `acosh`, `asinh`, `atanh`
Issue/s resolved: #776 
- Add `acosh`, `asinh`, `atanh`
- New feature
no
> add inverse hyperbolic functions

- CHANGELOG.md
- heat/core/exponential.py
- heat/core/tests/test_exponential.py
Adding square.
Just a monkey-coded cut&paste&edit from sqrt.
> adding square

- heat/core/dndarray.py
> getitem: define is_singular

- heat/core/types.py
Issue/s resolved: #803 
- factories.array -> dndarray.DNDarray
- code refactoring
yes / no
> types factories.array -> dndarray.DNDarray

- heat/core/communication.py
- heat/core/io.py
Issue/s resolved: #833 
bugfix
> Using global default comm in load_csv

- heat/core/dndarray.py
- heat/core/factories.py
Initial draft for from_partitioned.
> adding from_partitioned; aligning __partitioned__ with current spec

- CHANGELOG.md
- README.md
- heat/cluster/spectral.py
- heat/core/_operations.py
- heat/core/arithmetics.py
- heat/core/factories.py
- heat/core/linalg/qr.py
- heat/core/logical.py
- heat/core/manipulations.py
- heat/core/tests/test_io.py
- heat/core/tiling.py
- setup.py
Added capabilities to use torch 1.9.0. 
- minor changes to calls for floor divisions -> used divide with mode=floor
- minor text changes to call different functions
-
-
- Dependency adjustments
no
> Torch 1.9 upgrade

- CHANGELOG.md
- README.md
- heat/cluster/spectral.py
- heat/core/arithmetics.py
Updates for torch 1.10. No major breaking changes, hopefully no major issues
no
> updates for torch 1.10

- quick_start.md
quick_start.md was deleted by mistake with the latest merge of `release/1.2.x`  into `main`
- add the file back from earlier commit
-
-
-
Docs
NA
NA
no
> Reintroduce Quick Start

- heat/core/dndarray.py
- heat/core/tests/test_dndarray.py
- heat/optim/dp_optimizer.py
- setup.py
This PR fixes the following errors in the tests.
**1. `AttributeError: 'NoneType' object has no attribute 'data'`**
Due to a change in default behaviour of `torch.nn.Module.zero_grad()` as stated in the "Backwards Incompatible Changes" in the [2.0 release](https://github.com/pytorch/pytorch/releases/tag/v2.0.0)
**Solution:** Set `set_to_none` to `False` explicitly to preserve previous heat behaviour. 
Can also be modified to follow Pytorch and set the grads to `None` by default to reduce peak memory usage. But it would be a breaking change.
**2. `RuntimeError: a Tensor with * elements cannot be converted to Scalar`**
It is expected to raise a `ValueError`. But, it raises a `RuntimeError`. This change is not mentioned anywhere in the release notes. Even in the torch [source …
> Fixed bugs due to behaviour change in torch.nn.Module.zero_grad() and torch.Tensor.item() in torch 2.0

- heat/core/version.py
> Update version on `main` after releasing v1.3.0

- RELEASE.md
For future reference, taking note of the steps needed to release a new version of Heat. This is a live document while we're releasing v1.3.0
- introduce RELEASE.md
-
-
-
no
> Documentation: Release HowTo

- .github/workflows/changelog-updater.yml
- CHANGELOG.md
Action was not compatible with the existing changelog and workflow, and has been updated to fit the repo.
- Missing versions in the changelog have been copied from release notes. 
- changelog-updater action has been changed updated
-
-
- Github action change
no
> Changelog updater action fix

- .readthedocs.yaml
- heat/core/version.py
- General:
Merging latest changes from branch `release/1.3.x` into `main`.
- 
-
-
-
Bug fix
NA
NA
no
> Merge latest 1.3.x updates into `main`

- .github/ISSUE_TEMPLATE/bug_report.yml
- contributing.md
- quick_start.md
- General:
Small updates to `contributing` and `quick_start`. 
I propose an incremental update to our repo documentation,  merging even small changes as soon as they are ready. **DO NOT DELETE THIS BRANCH** after merging, we'll still use it.
We'll track changes in #1186  
- Notes on automated branch creation in `contributing.md` and `quick_start.md` 
-
-
-
NA
NA
no
> Repository docs update

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- README.md
- RELEASE.md
- contributing.md
- docker/README.md
- quick_start.md
- General:
Updated few `.md` files by fixing some grammatical mistakes, and followed [markdown linting](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) rules for better formatting of these files.
Added symbols to the titles of issue templates to make them look better.
Will look similar to this:
-
-
-
-
Documentation Update, fixing of simple grammatical errors to increase readability.
No.
> Fixed grammatical mistakes in few markdown files.

- .github/workflows/bench_report.yml
- .github/workflows/bench_trigger.yml
- .perun.ini
- benchmarks/cb/linalg.py
Aiming to improve reporting of CB benchmark results. They are hard to find and unreliable.
Changes to the two main action files, trigger benchmarks, and report benchmarks. (With changes on codebase side as well)
Issue/s resolved: #1213
> Improve single benchmark execution

- .github/ISSUE_TEMPLATE/vulnerability.yml
- SECURITY.md
- General:
Looking to better comply with the [community standards](https://github.com/helmholtz-analytics/heat/community).
- added instructions on how to submit a security vulnerability report
- added a dedicated Vulnerability Report template
-
-
NA
NA
no
> Add SECURITY.md and vulnerability report template

- README.md
- benchmarks/cb/main.py
- benchmarks/cb/preprocessing.py
This PR adds continuous benchmarking for the preprocessing module and therefore resolves #1246 
Monitoring memory consumption of the respective routines could be particularly interesting for #1184.
> Continuous Benchmarking for the Preprocessing Module

- heat/regression/lasso.py
Bug fix for #1258 
here to be merged into release; for the same bug fix to be merged into main see #1260
> Bug-fix for lasso on GPU

- RELEASE.md
- General:
Port the changes in README.md to release 1.3.x
-
-
-
-
yes / no
> Backport PR #1280 to release 1.3.x

- .github/dependabot.yml
- General:
Change the dependabot PRs to weekly update.
- dependabot.yml: set interval to weekly
- action workflow
no
> Change dependabot to weekly update

- .github/workflows/ReceivePR.yml
Trigger event ready for review
- General:
Trigger CI when PR is ready for review.
- update pull request trigger type
workflow
no
> Run tests when PR is ready for review

- .github/ISSUE_TEMPLATE/bug_report.yml
- heat/core/version.py
- General:
Issue/s resolved: #1385 
- set version back to 1.4.0-dev on `main`
- updated PyTorch, Python versions, removed outdated ones in Bug report template
-
-
Bug fix (non-breaking change which fixes an issue)
- 
NA
NA
no
> Set correct version on `main`, update Bug report template

- heat/core/version.py
> update version on main after release 1.4.x

- CHANGELOG.md
- heat/core/version.py
- General:
Update version number for bugfix release.
- update version.py
n/a
n/a
no
> Update version number

- .github/workflows/bench_report.yml
- .github/workflows/bench_trigger.yml
- General:
Update CB releated actions to better handle env variables and secrets.
- Small changes to bench_trigger.yml and bench_report.yml to better handle variables and secrets. 
- CB Actions
no
> Safety update for CB pipeline

- .github/workflows/ci.yaml
- setup.py
- General:
Support PyTorch 2.3.1
- Support latest PyTorch release
- Update ci.yaml
Dependency update
no
> Support PyTorch 2.3.1

- CHANGELOG.md
- General:
Adds the latest release to the changelog.
> Update CHANGELOG.md to v1.4.2

- .github/workflows/ci.yaml
- setup.py
Adapted CI-Matrix and setup.py accordingly
> Drop Python 3.8, Drop PyTorch < 2, Add Python 3.12 

- .github/workflows/ReceivePR.yml
Upgrades the Python version on the initial pretest.
CI
> Use python 3.9 in initial test run

- setup.py
- General:
Latest mpi4py 4.0.0 is not compatible with Heat.
- Set upper bound <4.0.0
- dependency update
> Set upper bound mpi4py <4.0.0

- tutorials/local/1_intro.ipynb
- General:
Initialised ipcluster with engines=mpi to fix the tutorial bug.
Issue/s resolved: #1673
-
-
-
-
no
> Update tutorials instructions for `ipcluster` initialization

- README.md
- RELEASE.md
- heat/core/version.py
- General:
Issue/s resolved: #1186 
- updated Requirements section on README
- updated RELEASE.md to match current workflow
no
> Documentation updates after new release

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/ci.yaml
- setup.py
> Support PyTorch 2.5.1 (#1701)

- .github/workflows/release-prep.yml
- General:
Adds reminders for alternative build systems to the post-release checklist:
- Docker
- conda-forge
- easy-build
- spack
Issue/s resolved: #1717
> Expanded post-release checklist

- heat/core/__init__.py
- heat/core/_config.py
- heat/core/communication.py
Created from #1793 after following the cherry-picking instructions.
> [Backport]  #1793 to stable

- doc/source/tutorials/notebooks/0_setup/0_setup_conda.sh
- doc/source/tutorials/notebooks/0_setup/0_setup_pip.sh
otherwise the script might install into the base environment
- General:
Issue/s resolved: #1879 
- exit install script if environment activation fails
-
-
-
- Bug fix
none
no
> Exit installation if conda environment cannot be activated

- .github/workflows/docker.yml
Reverts helmholtz-analytics/heat#1890
> Revert "build(deps): bump docker/setup-buildx-action from 3.10.0 to 3.11.1"

- .github/workflows/latest-pytorch-support.yml
- General:
release action: move to pyproject.toml
Issue/s resolved: #1940 
-
-
-
-
yes / no
> Move to pyproject.toml in release action
